apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http
  namespace: prox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-http
  template:
    metadata:
      labels:
        app: python-http
    spec:
      containers:
        - name: python-http
          image: python:3.9
          command: ["python", "-m", "http.server", "8000"]
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: python-http-service
  namespace: prox
spec:
  selector:
    app: python-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
